update validation scripts

diff --git a/validate/bpfwavelet_pcap b/validate/bpfwavelet_pcap
--- a/validate/bpfwavelet_pcap
+++ b/validate/bpfwavelet_pcap
@@ -1,5 +1,7 @@
-#!/bin/sh
-#
+#!/bin/bash
+set -Eeuo pipefail
+trap 'echo "${0}: Error on line ${LINENO}: ${BASH_COMMAND}" >&2' ERR
+
 # This script wraps bpfwavelet for testing its functionality.
 # It expects a pcap coming from stdin, the capture is then replayed through a
 # virtual interface where bpfwavelet is running, the detected periodicities are
@@ -10,34 +12,68 @@
 # Usage example:
 # `tcpdump -r capture.pcap -w - 'tcp port 49705' | sudo ./bpfwavelet_pcap` -v -t 100000000 -l 32`
 
-finish() {
-	[ -n "$NS" ] && ip netns delete "$NS" >&2
-	unset NS
-}
-trap finish INT TERM EXIT
-
-bpfwavelet_bin="$(dirname -- "$(realpath -- "$0")")"../src/bpfwavelet
-if [ ! -x "$bpfwavelet_bin" ]; then
-	echo "$bpfwavelet_bin not found" >&2
+if ((EUID)); then
+	echo "Need root priviliges" >&2
 	exit 1
 fi
 
-NS="$(mktemp --dry-run XXX)" # generate a random name to use as network namespace
-ip netns add "$NS" >&2
+cleanup() {
+	es="${?}"
+	trap '' EXIT INT QUIT TERM HUP
 
-VETH0='veth0'
-VETH1='veth1'
-ip netns exec "$NS" ip link add "$VETH0" type veth peer name "$VETH1" >&2
-ip netns exec "$NS" ip link set "$VETH0" up >&2
-ip netns exec "$NS" ip link set "$VETH1" up >&2
+	[ -n "${net_ns}" ] && ip netns delete "${net_ns}" >&2
+	unset net_ns
+
+	exit "${es}"
+}
+trap cleanup EXIT INT QUIT TERM HUP
+
+script_dir="$(dirname -- "$(realpath -- "${0}")")"
+bpfwavelet_bin="${script_dir}/../src/bpfwavelet"
+if [ ! -x "${bpfwavelet_bin}" ]; then
+	echo "${bpfwavelet_bin} not found" >&2
+	exit 1
+fi
+
+net_ns="$(mktemp --dry-run XXX)" # generate a random name to use as network namespace
+ip netns add "${net_ns}" >&2
+
+veth0='veth0'
+veth1='veth1'
+
+ip netns exec "${net_ns}" ip link add "${veth0}" type veth peer name "${veth1}" >&2
+
+ip netns exec "${net_ns}" ip link set "${veth0}" mtu 18000 >&2
+ip netns exec "${net_ns}" ip link set "${veth1}" mtu 18000 >&2
+
+# this is to avoid getting packets from neighbor discovery, IPv6 still works
+ip netns exec "${net_ns}" sysctl -w net.ipv6.conf."${veth0}".disable_ipv6=1 >&2
+ip netns exec "${net_ns}" sysctl -w net.ipv6.conf."${veth1}".disable_ipv6=1 >&2
+
+ip netns exec "${net_ns}" ip link set "${veth0}" up >&2
+ip netns exec "${net_ns}" ip link set "${veth1}" up >&2
 
 # run bpfwavelet in the background with the script arguments
-ip netns exec "$NS" "$bpfwavelet_bin" -d "$VETH1" "$@" &
-bpfwavelet_pid="$!"
+ip netns exec "${net_ns}" "${bpfwavelet_bin}" -g "${veth1}" "${@}" &
+bpfwavelet_pid="${!}"
 
-sleep 5
+check_attached() {
+	for _ in $(seq 100); do
+		ip netns exec "${net_ns}" ip link show "${veth1}" | grep --quiet xdpgeneric && return 0
+		sleep 0.1
+	done
+	return 1
+}
+if ! check_attached; then
+	echo "XDP code was not attached" >&2
+	exit 1
+fi
+
+ip netns exec "${net_ns}" ip addr show "${veth0}" >&2
+ip netns exec "${net_ns}" ip addr show "${veth1}" >&2
 
 # read pcap from stdin and replay it
-ip netns exec "$NS" tcpreplay --preload-pcap -i "$VETH0" - <&0 >&2
+ip netns exec "${net_ns}" tcpreplay -i "${veth0}" - <&0 >&2
 
-kill "$bpfwavelet_pid"
+sleep 2 # wait for in-flight packets
+kill "${bpfwavelet_pid}"
diff --git a/validate/run b/validate/run
--- a/validate/run
+++ b/validate/run
@@ -1,26 +1,23 @@
-#!/bin/sh
+#!/bin/bash
+set -Eeuo pipefail
+trap 'echo "${0}: Error on line ${LINENO}: ${BASH_COMMAND}" >&2' ERR
 
-script_location="$(dirname -- "$(realpath -- "$0")")"
-bpfwavelet_pcap_bin="${script_location}/bpfwavelet_pcap"
-mkdir -p "${script_location}/results"
+script_dir="$(dirname -- "$(realpath -- "${0}")")"
+invocation="$(date --iso-8601=seconds)"
+bpfwavelet_pcap_bin="${script_dir}/bpfwavelet_pcap"
 
-test() {
-	capture="$1"
-	filter="$2"
-	parameters="$3"
+mkdir -p "${script_dir}/results"
 
-	logfile="${script_location}/results/$(basename --suffix=.pcap "$capture")_$(echo "$filter" | tr -d '[:blank:]')_$(echo "$parameters" | tr -d '[:blank:]')"
+parameters='-t 100000000'
+for capture in captures/{cobalt-strike-filtered.pcap,heartbleed-full.pcap,trickbot-a-filtered.pcap,trickbot-b-filtered.pcap}; do
+	outfile="${script_dir}/results/$(basename --suffix=.pcap "${capture}")_$(echo "${parameters}" | tr -d '[:blank:]')_${invocation}"
+	errfile="${script_dir}/results/$(basename --suffix=.pcap "${capture}")_$(echo "${parameters}" | tr -d '[:blank:]')_${invocation}.err"
+	echo "saving to:"
+	echo "${outfile}"
+	echo "${errfile}"
+	sha256sum "${capture}"
 
-	tcpdump -r "$capture" -w - "$filter" | "$bpfwavelet_pcap_bin" -v $parameters >"$logfile" &
-}
-
-test captures/cobalt-strike.pcap '' '-t 250000000'
-
-test captures/trickbot-a.pcap '' '-t 250000000'
-
-test captures/trickbot-b.pcap '' '-t 250000000'
-
-test captures/heartbleed.pcap '' '-t 250000000'
-
-echo waiting for $(jobs -p)
-wait $(jobs -p)
+	echo "largest frame: $(tshark -r "${capture}" -T fields -e frame.len | sort -n | tail -1)" >"${errfile}"
+	capinfos -u -a -e "${capture}" >>"${errfile}"
+	"${bpfwavelet_pcap_bin}" ${parameters} <"${capture}" >"${outfile}" 2>>"${errfile}"
+done
